### ISSUE TITLE
Add "Contribution Guidelines"

### ISSUE THREAD

**Issue by src4026** [CTF-handbooks/ctf-handbooks.github.io#13]
- **Case 1**: Contribution with Writerside (Content writing + Build Process; commits must be separated for building and adding content in markdown)
- **Case 2**: Contributing without Writerside, i.e., plain markdown edits. For these, builds must be made separately by members with appropriate privs.

Also, will this information be included in the actual GitHub pages site?

**Comment by a-blob** [comment]
> Also, will this information be included in the actual GitHub pages site?

Sure! Why not :P
