### ISSUE TITLE
Missing licenses

### ISSUE THREAD

**Issue by Panquesito7** [CTF-handbooks/ctf-handbooks.github.io#14]
### Description

I'd suggest using:

- [MIT](https://opensource.org/license/MIT) for all the codebase.
- [CC BY 4.0 International](https://creativecommons.org/licenses/by/4.0/) for all the content.

Why use a license? Without a license, no one knows if they can contribute, use the content, or even share it.
You should check out https://opensource.guide/legal/ for more useful information.

**EDIT:** The license and author of the header image should also be mentioned somewhere on the readme/license files.

**Comment by a-blob** [comment]
The problem with MIT is that it doesn't require modifications to be open source. So a GNU General Public License might be better, and in this case, maybe a GNU Free Documentation License would be more suited?
@src4026 What do you think?

**Comment by src4026** [comment]
Hey Panq, thanks a lot for mentioning this. As @a-blob suggested, I'd also prefer the GNU General Public License coupled with the GNU Free Documentation License as the latter is specifically for OSS documentation. Sounds well suited.

**Comment by Panquesito7** [comment]
> Hey Panq, thanks a lot for mentioning this. As @a-blob suggested, I'd also prefer the GNU General Public License coupled with the GNU Free Documentation License as the latter is specifically for OSS documentation. Sounds well suited.

Sure! If that's what you prefer, feel free to do that. Thanks for taking care of this. :)

**Comment by Panquesito7** [comment]
Hmm, just one thing: I still don't see a license for the code, unless the GNU Free Documentation License is used for everything.

**Comment by src4026** [comment]
> Hmm, just one thing: I still don't see a license for the code, unless the GNU Free Documentation License is used for everything.

https://github.com/CTF-handbooks/ctf-handbooks.github.io/pull/16#issuecomment-2019323552
